openapi: 3.0.0
x-stoplight:
  id: mcnr59v9gcs0y
info:
  version: 1.0.0
  title: Client APIs
  description: ''
servers:
  - url: 'https://api.domo.com'
    description: Domo API
paths:
  /clients:
    post:
      summary: Create a Client
      description: Creates an OAuth client for use with the Get Access Token endpoint.
      operationId: post-clients
      parameters:
        - name: X-DOMO-Authentication
          in: header
          description: Session identifier from customer instance
          required: true
          schema:
            type: string
        - name: X-DOMO-CustomerDomain
          in: header
          description: Customer instance domain
          required: true
          schema:
            type: string
      requestBody:
        description: Definition of client to be created
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Human readable identifier of the client. Must be unique.
                  example: Automation
                description:
                  type: string
                  description: Long-form explanation of the purpose of the client.
                scope:
                  type: array
                  description: Control which scopes this client can grant access tokens
                  items:
                    enum:
                      - account
                      - audit
                      - buzz
                      - dashboard
                      - data
                      - user
                      - workflow
              required:
                - name
                - scope
      responses:
        '201':
          description: Client Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Human readable identifier of the client. Must be unique.
                  description:
                    type: string
                    description: Long-form explanation of the purpose of the client.
                  scope:
                    type: array
                    description: Scopes this client can grant access tokens
                    items:
                      enum:
                        - account
                        - audit
                        - buzz
                        - dashboard
                        - data
                        - user
                        - workflow
                  user:
                    type: integer
                    description: Id of user who created the client
                  client_id:
                    type: string
                    description: Client Identifier
                  client_secret:
                    type: string
                    description: Client Secret to be used for Client-Authenticated requests
                    format: password
                  authorized_grant_types:
                    type: array
                    description: Grant types supported by this client
                    items:
                      enum:
                        - client_credentials
                      example: client_credentials
                required:
                  - name
                  - scope
                  - client_id
                  - client_secret
                  - authorized_grant_types
                x-examples:
                  Example 1:
                    scope:
                      - data
                      - audit
                      - user
                      - dashboard
                    name: Client 1701240014
                    description: Autogenerated
                    user: 1589627109
                    role: Anonymous
                    client_id: d6e2a7d7-4fdc-4be6-baba-ff30bc44954f
                    client_secret: dac4726b800462422b127e1ff3c17456af74d789c4d86899080acee0e8aed5f1
                    authorized_grant_types:
                      - client_credentials
      security: []
      servers:
        - url: 'https://api.domo.com'
          description: Domo API
      x-stoplight:
        id: 1ct5gv8jac5yx
components:
  securitySchemes:
    API Key - 1:
      type: http
      scheme: basic
security:
  - API Key - 1: []
