openapi: 3.1.0
x-stoplight:
  id: khlmozruuyfrz
info:
  title: S3 Export API
  version: '1.0'
  summary: A set of endpoints for exporting DataSets to S3
servers:
  - url: 'https://api.domo.com'
    description: Domo API
paths:
  '/api/query/v1/export/{dataset_id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-api-query-v1-export
    parameters:
      - schema:
          type: string
        name: dataset_id
        in: path
        required: true
        description: The id of the dataset to export to s3
    post:
      summary: Export DataSet to S3
      operationId: post-api-query-v1-export-dataset_id
      responses:
        '200':
          description: 'The exportId is returned to you as a response to this call. '
          content:
            application/json:
              schema:
                type: object
                properties:
                  exportId:
                    type: string
                    description: The id for this export
                  exportStatus:
                    type: string
                    description: 'The status for this export. Allowed values are `none`, `exporting`, `success`, `error`'
                  errorCode:
                    type: string
                    description: This is an internal error code that can be used to help diagnose issues.
                  message:
                    type: string
                    description: This is the descriptive error message.
                  started:
                    type: string
                    description: ' Date the export was started. Time in milliseconds since midnight January 1, 1970.'
                  finished:
                    type: string
                    description: 'Date the export completed. Time in milliseconds since midnight January 1, 1970.'
                  compression:
                    type: string
                    description: 'The compression data was stored in. Allowed values are `none`, `gzip`.'
                  bucket:
                    type: string
                    description: The bucket the exported results are stored in
                  exportFormat:
                    type: string
                    description: The format the export results are stored in. Allowed values are `csv`
                  urlRowCountMap:
                    type: string
                    description: The URL(s) to the exported files along with their row count.
      description: |
        Starts an export of your dataset to an S3 device of your choosing. This is an asynchronous call.

        ### Limitations  

        - You can have only one actively running export for a given `dataset_id` at a time.  
        - If you make a request to export a `dataset_id` and the data in the dataset hasn't changed since the last export this endpoint will return the export information for that previous export, a new download will not be created.

        ### Security Considerations

        - You should use temporary AWS credentials whenever possible.  If the credentials are temporary you must also provide an AWS session token.
        - In order to export a dataset, the user must have at least read access.
        - Any PDP policies that exist will be applied to the exported data.

        <!-- theme: warning -->
        > #### Watch Out!
        >
        > Once the data is exported, the only security around the data is what is provided by the AWS S3 bucket.  This means you must carefully consider the security of the export location.  You should not upload data to an S3 location that others can view who should not have access to the data that is contained in the upload.
        >
        > **Example**: Say you have a dataset that contains compensation information.  You have carefully limited those who have access to the dataset in the DOMO system.  You have also applied PDP policies so that managers can only see the compensation information in the dataset based on your reporting structure. Then an administrator initiates an export to an S3 location.  However the admin provides an S3 location that the entire company has access to.  Now the the entire company can see the compensation information tracked in this dataset.  The security provided by the DOMO system is now voided.
      x-internal: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                  description: Path to place exported data in.  The value in this field will replace what is in the <path> placeholder in the following <bucket>/<path>/<exportId>/export/data.csv.gz. If not specified the path will be the dataSourceId
                bucket:
                  type: string
                  description: 's3 bucket to put data in. If not specified, A Domo configured bucket for customer will be used.  The bucket must already be created.'
                awsAccessKey:
                  type: string
                  description: The access key to the customer's s3. This is used one time and is not stored in the system.  The client should use short term or one time credentials for the export api.  If you are use temporary credentials you must also provide a session token.
                awsAccessSecret:
                  type: string
                  description: The access secret to the customer's s3.  This is used one time and is not stored in the system. The client should use short term or one time credentials for the export api.  If you are use temporary credentials you must also provide a session token.
                awsKmsKey:
                  type: string
                  description: The kms key id to the customer's s3 kms key.  This is used one time and is not stored in the system.
                sessionToken:
                  type: string
                  description: The session token to the customer's s3.  This is used one time and is not stored in the system. The client should use short term or one time credentials for the export api.   If you are use temporary credentials you must also provide a session token.
                region:
                  type: string
                  description: The AWS region of the bucket.
                queryRequest:
                  type: string
                  description: 'The "QueryRequest". See documentation for POST /api/query/v1/execute/{dataSourceId}'
                source:
                  type: string
                  description: The source requesting the export
          application/xml:
            schema:
              type: object
              properties: {}
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      type: http
      scheme: bearer
security:
  - API Key - 1: []
