def handle_help_cli(*args, **kwargs):
    """
    Print the help message for the CLI.
    """
    print("\nDomo Vector CLI - Manage documents and images in Domo vector indexes and filesets\n")
    print("Usage: domo-vector <command> [options]\n")
    print("Setup:")
    print("  configure              Set up your Domo API credentials and instance URL\n")
    print("Vector Index Commands:")
    print("  vector upload          Chunk and upload documents/images to a vector index")
    print("                         Supports: .md, .html, .json, .pdf, .txt files")
    print("                         Images: .png, .jpg, .jpeg, .gif, .bmp, .webp, .tiff (with --include-images)")
    print("  vector delete-all      Delete all nodes from an index")
    print("  vector delete-by-id    Delete specific nodes by their IDs")
    print("  vector delete-by-group Delete nodes by group ID")
    print("  vector get-all         List all node IDs in an index\n")
    print("Fileset Commands:")
    print("  fileset create         Create a new fileset")
    print("  fileset upload-file    Upload files or directories to a fileset")
    print("  fileset get-file       Download a file from a fileset")
    print("  fileset get-fileset    Get fileset metadata and information")
    print("  fileset get-filesets   List all available filesets")
    print("  fileset search-filesets Search filesets with pagination\n")
    print("Examples:")
    print("  domo-vector configure")
    print("  domo-vector vector upload --source-dir ./docs --include-images")
    print("  domo-vector fileset create --name 'Documentation' --description 'Project docs'\n")
    print("Use 'domo-vector <command> --help' for detailed options and parameters.")
