def handle_help_cli(*args, **kwargs):
    """
    Print the help message for the CLI.
    """
    print("\nDomo Vector CLI - Manage documents and images in Domo vector indexes and filesets\n")
    print("Usage: domo-vector <command> [options]\n")
    
    print("SETUP:")
    print("  configure              Set up your Domo API credentials and instance URL")
    print("                         • Interactive prompts for token and instance")
    print("                         • Creates .env file with configuration\n")
    
    print("VECTOR INDEX COMMANDS:")
    print("  vector upload --source-dir <path> [options]")
    print("                         Chunk and upload documents/images to a vector index")
    print("    Required arguments:")
    print("      --source-dir PATH    Source directory containing files to process")
    print("    Optional arguments:")
    print("      --index-id ID        Vector index ID (default: uses VECTOR_INDEX_ID from .env)")
    print("      --include-images     Process image files (.png, .jpg, .jpeg, .gif, .bmp, .webp, .tiff)")
    print("      --dry-run           Preview what would be uploaded without uploading")
    print("      --no-create-index   Skip index creation, upload to existing index only")
    print("      --chunk-size N      Max characters per text chunk (default: 1500)")
    print("      --overlap N         Overlapping characters between chunks (default: 200)")
    print("      --group-id ID       Group ID for uploaded nodes (default: filename)")
    print("    Supported files: .md, .html, .json, .pdf, .txt\n")
    
    print("  vector delete-all --index-id <id>")
    print("                         Delete ALL nodes from an index")
    print("  vector delete-by-id --index-id <id> --node-ids <id1> <id2> ...")
    print("                         Delete specific nodes by their IDs")
    print("  vector delete-by-group --index-id <id> --group-ids <group1> <group2> ...")
    print("                         Delete nodes by group ID")
    print("  vector get-all --index-id <id>")
    print("                         List all node IDs in an index\n")
    
    print("FILESET COMMANDS:")
    print("  fileset create --name <name> [--description <desc>]")
    print("                         Create a new fileset")
    print("  fileset upload-file --fileset-id <id> --file-path <path>")
    print("                         Upload a single file to fileset")
    print("  fileset upload-file --fileset-id <id> --directory <path>") 
    print("                         Upload entire directory to fileset")
    print("  fileset get-file --fileset-id <id> --file-path <path>")
    print("                         Download file by path from fileset")
    print("  fileset get-file --fileset-id <id> --file-id <id>")
    print("                         Download file by ID from fileset")
    print("  fileset get-fileset --fileset-id <id>")
    print("                         Get fileset metadata and information")
    print("  fileset get-filesets   List all available filesets")
    print("  fileset search-filesets [--limit N] [--offset N] [--name <search_term>]")
    print("                         Search filesets with pagination and name filtering\n")
    
    print("EXAMPLES:")
    print("  domo-vector configure")
    print("  domo-vector vector upload --source-dir ./docs")
    print("  domo-vector vector upload --source-dir ./docs --include-images --dry-run")
    print("  domo-vector vector delete-all --index-id my-index")
    print("  domo-vector fileset create --name 'Documentation' --description 'Project docs'\n")
    
    print("For more detailed help on any command, use:")
    print("  domo-vector <command> <subcommand> --help")
