openapi: 3.1.0
x-stoplight:
  id: 4wu6c4ddtn4m3
info:
  title: Workflows Product API
  version: '1.0'
  summary: ''
  description: |-
    This API reference is useful if you are trying to hit workflows from:
    1. An external Domo Instance
    2. A environment from outside of Domo
    2. A script running in Domo's Jupyter Workspaces

    If you are looking to hit a workflow from a Domo App, see the [App Framework API Reference for Workflows](../../Domo-App-APIs/Workflows-API.md) and the [guide on how to hit a workflow from a Domo App](../../Apps/App-Framework/Guides/hitting-a-workflow.md).

    If you are unfamiliar with how to authenticate against Product APIs, [please see this overview page](../../Getting-Started/api-authentication.md).

    For more background on Workflows, check out the [Knowledge Base for an overview](https://domo-support.domo.com/s/article/000005108?language=en_US). 
servers:
  - url: 'https://YOUR_INSTANCE.domo.com/api/workflow/v1/'
    description: Workflows Product API
paths:
  /instances/message:
    post:
      summary: Start a Workflow
      tags: []
      responses:
        '200':
          description: |-
            Returns the information about the instance of the Workflow that was just started. The `status` property can take the values `null`, `IN_PROGRESS`, `CANCELED`,  or `COMPLETED`. 

            A status of `null` might be valid. It just means the workflow hasn’t reported back as started yet.


            ```json
            HTTP/1.1 200 OK
            Content-Type: application/json;charset=UTF-8

            {
                "id": "2052e10a-d142-4391-a731-2be1ab1c0188", // id of the workflow
                "modelId": "a8afdc89-9491-4ee4-b7c3-b9e9b86c0138", // id of the workflow instance
                "modelName": "AddTwoNumbers", // name of the workflow
                "modelVersion": "1.1.0", // workflow version number
                "createdBy": "8811501", // user id of workflow creator
                "createdOn": "2023-11-15T15:28:57.479Z",
                "updatedBy": "8811501",
                "updatedOn": "2023-11-15T15:28:57.479Z",
                "status": "null"
            }
            ```
      operationId: post-instances-message
      x-stoplight:
        id: 5s59dpkk1hmx6
      description: |-
        Starts a Workflow and returns details about the Workflow Instance.

        <!-- theme: warning -->
        > #### Server-side only
        >
        > These APIs are CORS restricted so should only be called server-side when scripting against Domo. Due to this restriction, the "Try It" functionality in this documentation will not work, but the code snippet it generates (e.g. the curl request) should provided that you replace `YOUR_INSTANCE` and `YOUR_TOKEN` with the appropriate values.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - messageName
                - version
                - modelId
                - data
              properties:
                messageName:
                  type: string
                  x-stoplight:
                    id: 86i8jspiqzz7z
                  description: 'Message passed to start the Workflow Instance, usually `"Start {workflow_name}`'
                version:
                  type: string
                  x-stoplight:
                    id: rcooglugturnd
                  description: The version identifier e.g. `0.0.1`
                modelId:
                  type: string
                  x-stoplight:
                    id: 9y13a38612ny2
                  description: The id of the Workflow Instance
                data:
                  type: object
                  x-stoplight:
                    id: yp9kk81bsfgno
                  description: |-
                    The start parameters required to kick off the Workflow. A simple example of a workflow that takes two numerical inputs, might look like the following:
                    ```json
                    {"parameter1": 13, "parameter2": 7}
                    ```

                    #### Input Parameters

                    > For the `data` object containing the start parameters required to run the workflow, be careful to structure this object so it is consistent with the input types that you've already defined in your workflow.
                    >
                    > The valid input type options are:
                    > - `boolean`
                    > - `date`
                    > - `dateTime`
                    > - `decimal`
                    > - `duration`
                    > - `number`
                    > - `object`
                    > - `person`
                    > - `dataset`
                    > - `group`
                    > - `text`
                    > - `time`
                    >
                    > You may pass in lists containing the above types and may also nest additional information in `object` type inputs.
            examples:
              Example 1:
                value:
                  messageName: Start AddTwoNumbers
                  version: 1.1.0
                  modelId: a8afdc89-9491-4ee4-b7c3-b9e9b86c0138
                  data:
                    num1: 1
                    num2: 2
        description: ''
    servers:
      - url: 'https://YOUR_INSTANCE.domo.com/api/workflow/v1/'
        description: ''
    parameters:
      - schema:
          type: string
          default: YOUR_TOKEN
        in: header
        name: X-DOMO-Developer-Token
        description: 'You can find out more about generating a developer token at `https://domo-support.domo.com/s/article/360042934494?language=en_US` '
        required: true
components:
  schemas: {}
